ARG openshift_version
FROM registry.redhat.io/openshift4/ose-operator-registry:${openshift_version}

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

COPY catalog/ /configs
LABEL operators.operatorframework.io.index.configs.v1=/configs

# Build the cache such that we can use this image as the target for a standalone CatalogSource.
RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]
