---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-12-rxjqm
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-12
    appstudio.openshift.io/component: operator-index-ocp-v4-12
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-12-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-12
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:8a936df732c8c409389660061e5fb95a41c756ceff6d1ccb2c6bb3dc89754f8d
      name: operator-index-ocp-v4-12
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-12-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-12
  snapshot: acs-operator-index-ocp-v4-12-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-13-tc4x2
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-13
    appstudio.openshift.io/component: operator-index-ocp-v4-13
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-13-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-13
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:97a75e552360d277c190ebd0ff601bbf1850b5ee38a73892e275d92b4f531bf3
      name: operator-index-ocp-v4-13
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-13-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-13
  snapshot: acs-operator-index-ocp-v4-13-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-14-q5prc
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-14
    appstudio.openshift.io/component: operator-index-ocp-v4-14
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-14-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-14
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:c96908af3302ff195692adcc64a9e5801d63c51c27eb5f9d5966198ef67a99b5
      name: operator-index-ocp-v4-14
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-14-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-14
  snapshot: acs-operator-index-ocp-v4-14-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-15-8tr8d
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-15
    appstudio.openshift.io/component: operator-index-ocp-v4-15
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-15-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-15
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:30ee14fd1764d67b0f56f93c585a02cbaddedd235e9b2d4da9faa0bd02fd7b01
      name: operator-index-ocp-v4-15
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-15-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-15
  snapshot: acs-operator-index-ocp-v4-15-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-16-4lnz8
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-16
    appstudio.openshift.io/component: operator-index-ocp-v4-16
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-16-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-16
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:f0999db65a406168ddc6560aea37ffeed79ebd4b125d5170e873a219630b99a1
      name: operator-index-ocp-v4-16
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-16-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-16
  snapshot: acs-operator-index-ocp-v4-16-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-17-89ngj
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-17
    appstudio.openshift.io/component: operator-index-ocp-v4-17
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-17-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-17
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:7b37292eedd06e828370e7108a3a62d468c7797bd82321865796f16158fd1171
      name: operator-index-ocp-v4-17
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-17-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-17
  snapshot: acs-operator-index-ocp-v4-17-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-18-9thq7
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-18
    appstudio.openshift.io/component: operator-index-ocp-v4-18
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-18-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-18
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:d944c8b611eda4fdb6aab0dc13984e3f68e7d075e60babee772e35945409e125
      name: operator-index-ocp-v4-18
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-18-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-18
  snapshot: acs-operator-index-ocp-v4-18-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-19-vclsr
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-19
    appstudio.openshift.io/component: operator-index-ocp-v4-19
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-19-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-19
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:506b9d2dcc192e0860e91c2fdce98959b82762a650f039acb9b69dba6a5d1115
      name: operator-index-ocp-v4-19
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-19-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-19
  snapshot: acs-operator-index-ocp-v4-19-20251208-prod-c1acf8e
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: kurlov
    pac.test.appstudio.openshift.io/sha-title: 'ROX-30064: Script to generate catalog-template.yaml (#137)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/c1acf8e18845d6b14edf914160cc248211a77982
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-20-7rk6k
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-20
    appstudio.openshift.io/component: operator-index-ocp-v4-20
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: c1acf8e18845d6b14edf914160cc248211a77982
  name: acs-operator-index-ocp-v4-20-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-20
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:f46339960327f7122b18b405aed84ed9a60db62df5bf31eb4f753915cdb449df
      name: operator-index-ocp-v4-20
      source:
        git:
          revision: c1acf8e18845d6b14edf914160cc248211a77982
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-20-20251208-prod-c1acf8e
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-prod-ocp-v4-20
  snapshot: acs-operator-index-ocp-v4-20-20251208-prod-c1acf8e
