---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-12-n65gx
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-12
    appstudio.openshift.io/component: operator-index-ocp-v4-12
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-12-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-12
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:58b85359ad3e3807947a2a83e11c86a4600008ee5d1b39806871fdd3cb1be387
      name: operator-index-ocp-v4-12
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-12-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-12
  snapshot: acs-operator-index-ocp-v4-12-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-13-9prdz
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-13
    appstudio.openshift.io/component: operator-index-ocp-v4-13
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-13-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-13
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:c5e77d21a13620f4c1a43105ffa30ae42d8da8b1a19ac0d87c23fc15c35fdc67
      name: operator-index-ocp-v4-13
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-13-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-13
  snapshot: acs-operator-index-ocp-v4-13-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-14-x2rf4
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-14
    appstudio.openshift.io/component: operator-index-ocp-v4-14
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-14-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-14
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:d6b6675d2fa72ca573172692f20874140a8a677b946bc71df4d142755c707caf
      name: operator-index-ocp-v4-14
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-14-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-14
  snapshot: acs-operator-index-ocp-v4-14-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-15-265qx
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-15
    appstudio.openshift.io/component: operator-index-ocp-v4-15
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-15-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-15
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:90947f1937058be65b4199dff55b0519271467fa163da2951aa8b9948832ca66
      name: operator-index-ocp-v4-15
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-15-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-15
  snapshot: acs-operator-index-ocp-v4-15-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-16-5dj6d
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-16
    appstudio.openshift.io/component: operator-index-ocp-v4-16
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-16-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-16
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:fe6938193d5f0980f77a4bc5dfaaeaa84bec59c7906c844359465ba04586e0ad
      name: operator-index-ocp-v4-16
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-16-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-16
  snapshot: acs-operator-index-ocp-v4-16-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-17-khf2r
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-17
    appstudio.openshift.io/component: operator-index-ocp-v4-17
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-17-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-17
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:d1f0d47f1c2bd228ec9f25932bde282ff07b2b5ae6f4cefbd8a1a04e1d3a7cfe
      name: operator-index-ocp-v4-17
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-17-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-17
  snapshot: acs-operator-index-ocp-v4-17-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-18-sjkdn
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-18
    appstudio.openshift.io/component: operator-index-ocp-v4-18
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-18-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-18
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:9e6f01028ee3e32f6220b5a2688debce283057615516db716aa0ecc3c7f5ac5f
      name: operator-index-ocp-v4-18
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-18-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-18
  snapshot: acs-operator-index-ocp-v4-18-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-19-2wp66
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-19
    appstudio.openshift.io/component: operator-index-ocp-v4-19
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-19-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-19
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:d7b3ca595a65c3b5b4fe97e78cc8ee260b6c797c70a0cb0312fcc9239c896fc4
      name: operator-index-ocp-v4-19
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-19-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-19
  snapshot: acs-operator-index-ocp-v4-19-20251117-stage-ca32cae
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/sender: red-hat-konflux[bot]
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update quay.io/konflux-ci/release-service-utils:latest docker digest to 26206bd'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stackrox/operator-index/commit/ca32cae25ebf8b6a743f19482b851837dc25fc4a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    acs.redhat.com/original-snapshot-name: acs-operator-index-ocp-v4-20-5829c
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-20
    appstudio.openshift.io/component: operator-index-ocp-v4-20
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/sha: ca32cae25ebf8b6a743f19482b851837dc25fc4a
  name: acs-operator-index-ocp-v4-20-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  application: acs-operator-index-ocp-v4-20
  artifacts: {}
  components:
    - containerImage: quay.io/rhacs-eng/stackrox-operator-index@sha256:f617a0ec1acf2f43bf1362456719e60058c03edb92e144f23ca31f73dfd9808c
      name: operator-index-ocp-v4-20
      source:
        git:
          revision: ca32cae25ebf8b6a743f19482b851837dc25fc4a
          url: https://github.com/stackrox/operator-index

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: acs-operator-index-ocp-v4-20-20251117-stage-ca32cae
  namespace: rh-acs-tenant
spec:
  releasePlan: acs-operator-index-stage-ocp-v4-20
  snapshot: acs-operator-index-ocp-v4-20-20251117-stage-ca32cae
