apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: check-generated-files-up-to-date
  namespace: rh-acs-tenant
spec:
  description: Runs `make` to regenerate files and verifies that no checked in files differ afterwards.
  params:
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with
      the application source code. This should be the result of the git-clone task,
      results from other tasks might fail as dirty.
    type: string
  volumes:
  - name: workdir
    emptyDir: { }
  - name: deps
    emptyDir: { }
  stepTemplate:
    volumeMounts:
    - mountPath: /var/workdir
      name: workdir
    - mountPath: /var/deps
      name: deps
  steps:
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
    args:
    - use
    - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - name: check-generated-files-up-to-date
    image: registry.access.redhat.com/ubi8:latest
    workingDir: /var/workdir/source
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      set -x
      OPM_VERSION="1.48.0"
      os_name=linux
      arch=amd64

      time dnf -y upgrade --nobest
      # TODO: find an image with these preinstalled to reduce flakiness
      time dnf -y install git make jq curl

      cd /var/deps
      for attempt in $(seq 5); do
        if time curl --silent --fail --location --output opm "https://github.com/operator-framework/operator-registry/releases/download/v${OPM_VERSION}/${os_name}-${arch}-opm"; then
          break
        fi
      done
      chmod +x opm
      export PATH="$PATH:$(pwd)"
      cd -
      
      time make clean
      cmd="make valid-catalogs"
      time $cmd
      set +x
      if ! git diff --exit-code HEAD; then
        git diff --stat HEAD || true
        echo >&2 "Some generated files are not up to date with their source ^^^. Run '$cmd' to update them."
        exit 1
      fi
