apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/operator-index?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    # The on-push filter includes konflux/* branches which are created by Mintmaker so that CI runs for commits pushed
    # onto these branches even without PRs and so that Mintmaker/Renovate can automerge its updates without PRs.
    pipelinesascode.tekton.dev/on-cel-expression: |
      (event == "push" && target_branch.matches("^(master|konflux/references/master|konflux/mintmaker/.*)$")) ||
      (event == "pull_request" && body.action != "ready_for_review")
  labels:
    # The version should correspond to the serviceAccountName below. See the comment there.
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-19
  name: checks
  namespace: rh-acs-tenant

spec:

  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'

  taskRunTemplate:
    # This pipeline doesn't have its own Component, but it has to have some ServiceAccount.
    # The pipeline has no special needs for SA, therefore, we re-use SA from one of the existing Components.
    serviceAccountName: build-pipeline-operator-index-ocp-v4-19

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  pipelineSpec:
    description: |
      This pipeline performs checks not specific to any OCP version.

    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - description: Revision of the Source Repository
      name: revision
      type: string
    - default: quay.io/rhacs-eng/stackrox-operator-index
      description: Intermediate Image Repository
      name: oci-repo
      type: string
    - default: "1d"
      description: This sets the expiration time for intermediate OCI artifacts produced and used during builds after
        which they can be garbage collected.
      name: oci-artifact-expires-after
      type: string

    workspaces:
    - name: git-auth

    tasks:

    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      - name: ociStorage
        value: $(params.oci-repo):konflux-checks-$(params.revision).git
      - name: ociArtifactExpiresAfter
        value: $(params.oci-artifact-expires-after)
      taskRef:
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:2c388d28651457db60bb90287e7d8c3680303197196e4476878d98d81e8b6dc9
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: basic-auth
        workspace: git-auth

    - name: run-go-unit-tests
      taskSpec:
        metadata:
          name: run-go-unit-tests
        volumes:
        - name: workdir
          emptyDir: { }
        stepTemplate:
          volumeMounts:
          - mountPath: /var/workdir
            name: workdir
        steps:
        - name: use-trusted-artifact
          image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
          args:
          - use
          - $(tasks.clone-repository.results.SOURCE_ARTIFACT)=/var/workdir/source
        - name: run-go-tests
          image: registry.redhat.io/ubi9/go-toolset@sha256:8c5aeac74b4b60dc2e5e44f6b639186b7ec2fec8f0eb9a36d4a32dcf8e255f52
          workingDir: /var/workdir/source
          script: time make go-test

    - name: check-generated-files-up-to-date
      params:
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      # Retries are for the cases when opm alpha render-template occasionally fails to pull images.
      retries: 3
      taskRef:
        name: check-generated-files-up-to-date

    - name: validate-pipeline-files
      params:
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        name: validate-pipeline-files

    - name: check-catalog-file-size
      taskSpec:
        volumes:
        - name: workdir
          emptyDir: { }
        stepTemplate:
          volumeMounts:
          - mountPath: /var/workdir
            name: workdir
        steps:
        - name: use-trusted-artifact
          image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
          args:
          - use
          - $(tasks.clone-repository.results.SOURCE_ARTIFACT)=/var/workdir/source
        - name: check-catalog-file-size
          image: registry.redhat.io/ubi9/ubi-minimal@sha256:d91be7cea9f03a757d69ad7fcdfcd7849dba820110e7980d5e2a1f46ed06ea3b
          workingDir: /var/workdir/source
          script: |
            #!/usr/bin/env bash
            set -euo pipefail

            echo "Checking Catalog file sizes...

            If this check fails, it means ACS likely contributes significant part to the size of the catalog image.
            If we let our part of catalog grow uncontrollably, it _may_ cause problems anywhere in the supply
            chain or on customers clusters. We don't know when it happens and how big the impact would be
            but we don't want to be the ones who find this all out. Hence we put this check in place.

            When this check fails for you, you obviously want to proceed further with whatever important you
            do. You may bump the limit just a bit to let your catalog update go through. It should be fine, we
            started with somewhat conservative limits for you. Say, do +10MB or +10% limit increase.
            If your update is bigger than that, it's time to stop and reconsider whatever you are doing.

            Right next after bumping the limit, you ought to pay the debt. Reach out to relevant ACS teams
            (e.g., the Install team) and reach out to the OLM team to find out whether this size of the catalog
            is safe or can cause issues and come up with a plan if the latter.
            "

            max_old_format_size_mb="50"
            max_new_format_size_mb="28"

            old_format_file="catalog-bundle-object/rhacs-operator/catalog.json"
            new_format_file="catalog-csv-metadata/rhacs-operator/catalog.json"

            du -h "$old_format_file" "$new_format_file"

            old_format_file_size_mb="$(stat -c %s "$old_format_file" | numfmt --to-unit=1M)"
            new_format_file_size_mb="$(stat -c %s "$new_format_file" | numfmt --to-unit=1M)"

            if [[ "$old_format_file_size_mb" -gt "$max_old_format_size_mb" ]]; then
              echo >&2 "ERROR: ${old_format_file} is bigger than ${old_format_file_size_mb}"
              exit 1
            fi

            if [[ "$new_format_file_size_mb" -gt "$max_new_format_size_mb" ]]; then
              echo >&2 "ERROR: ${new_format_file} is bigger than ${max_new_format_size_mb}"
              exit 1
            fi

            echo "All catalog files are within their size limits"
