---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: quay-proxy
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/rhacs-eng/stackrox-operator-bundle
      source: registry.redhat.io/advanced-cluster-security/rhacs-operator-bundle
