apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/operator-index?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "master" && ( "common/***".pathChanged() || ".tekton/operator-index-ocp-v4-16-pull-request.yaml".pathChanged()
      )
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-16
    appstudio.openshift.io/component: operator-index-v4-16
    pipelines.appstudio.openshift.io/type: build
  name: operator-index-ocp-v4-16-on-pull-request
  namespace: rh-acs-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: openshift-version
    value: v4.16
  - name: output-image
    value: quay.io/rhacs-eng/stackrox-operator-index:ocp-v4-16-{{revision}}-fast
  - name: image-expires-after
    # TODO(ROX-24530): set expiration consistently
    value: 5d

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineRef:
    name: operator-index-pipeline
