apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: operator-index-pipeline

spec:

  description: |
    This pipeline builds and verifies ACS operator [file-based catalogs](https://konflux-ci.dev/docs/advanced-how-tos/building-olm.adoc#building-the-file-based-catalog).
    Modified from the generic Konflux pipeline by adding an OpenShift version parameter.

    _Uses `buildah` to create a container image. Its build-time tests are limited to verifying the included catalog and do not scan the image._

  finally:

  - name: slack-notification
    params:
    - name: message
      value: ':x: `{{event_type}}` pipeline for <https://console.redhat.com/application-pipeline/ns/$(context.pipelineRun.namespace)/pipelinerun/$(context.pipelineRun.name)|$(context.pipelineRun.name)> (`$(params.output-image-repo)`, revision <$(params.git-url)/commit/$(params.revision)|$(params.revision)>) has failed.'
    - name: key-name
      value: 'acs-konflux-notifications'
    when:
    # Run when any task has Failed
    - input: $(tasks.status)
      operator: in
      values: ["Failed"]
    taskRef:
      params:
      - name: name
        value: slack-webhook-notification
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-slack-webhook-notification:0.1@sha256:dc17b70633363d78414b8c06dc1660d25742935f106a6116995638e1210c2730
      - name: kind
        value: task
      resolver: bundles

  - name: show-sbom
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    taskRef:
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:04f15cbce548e1db7770eee3f155ccb2cc0140a6c371dc67e9a34d83673ea0c0
      - name: kind
        value: task
      resolver: bundles

  - name: show-summary
    params:
    - name: pipelinerun-name
      value: $(context.pipelineRun.name)
    - name: git-url
      value: $(tasks.clone-repository.results.url)?rev=$(tasks.clone-repository.results.commit)
    - name: image-url
      value: $(params.output-image-repo):$(params.output-image-tag)
    - name: build-task-status
      value: $(tasks.build-image-index.status)
    taskRef:
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-summary:0.2@sha256:870d9a04d9784840a90b7bf6817cd0d0c4edfcda04b1ba1868cae625a3c3bfcc
      - name: kind
        value: task
      resolver: bundles

  - name: post-metric-end
    params:
    - name: AGGREGATE_TASKS_STATUS
      value: $(tasks.status)
    taskRef: &post-bigquery-metrics-ref
      params:
      - name: name
        value: post-bigquery-metrics
      - name: bundle
        value: quay.io/rhacs-eng/konflux-tasks:latest@sha256:fd4399e9b77dac8efcf0ef2149569099e9d7424f19dc64ec8a9d5888ab160ad8
      - name: kind
        value: task
      resolver: bundles

  params:
  - description: Source Repository URL
    name: git-url
    type: string
  - default: ""
    description: Revision of the Source Repository
    name: revision
    type: string
  - description: Output Image Tag. Will be qualified with output-image-repo.
    name: output-image-tag
    type: string
  - default: quay.io/rhacs-eng/stackrox-operator-index
    description: Output Image Repository
    name: output-image-repo
    type: string
  - default: .
    description: Path to the source code of an application's component from where to build image.
    name: path-context
    type: string
  - default: catalog.Containerfile
    description: Path to the Dockerfile inside the context specified by parameter path-context.
    name: dockerfile
    type: string
  - description: Pull spec to use for the base image.
    name: base-image
    type: string
  - description: Catalog dir to use for building image.
    name: catalog-dir
    type: string
  - default: "false"
    description: Force rebuild image
    name: rebuild
    type: string
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "true"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ""
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and
      weeks, respectively.
    name: image-expires-after
    # Image expiry disabled because it sets quay.expires-after label on the image which fails Conforma at release time.
    # A downside is that FBC images will stay in our Quay forever while certainly they become unneeded as time passes.
    # TODO(ROX-27836): find a way to garbage-collect FBC images.
    default: ''
  - default: "false"
    description: Build a source image.
    name: build-source-image
    type: string
  - default: "true"
    description: Add built image into an OCI image index
    name: build-image-index
    type: string
  - default: "1d"
    description: This sets the expiration time for intermediate OCI artifacts produced and used during builds after
      which they can be garbage collected.
    name: oci-artifact-expires-after
    type: string
  - default:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
    description: List of platforms to build the container images for. The available
      set of values is determined by the configuration of the multi-platform-controller.
    name: build-platforms
    type: array

  results:
  - description: ""
    name: IMAGE_URL
    value: $(tasks.build-image-index.results.IMAGE_URL)
  - description: ""
    name: IMAGE_DIGEST
    value: $(tasks.build-image-index.results.IMAGE_DIGEST)
  - description: ""
    name: CHAINS-GIT_URL
    value: $(tasks.clone-repository.results.url)
  - description: ""
    name: CHAINS-GIT_COMMIT
    value: $(tasks.clone-repository.results.commit)

  workspaces:
  - name: git-auth

  tasks:

  - name: post-metric-start
    taskRef: *post-bigquery-metrics-ref

  - name: init
    params:
    - name: image-url
      value: $(params.output-image-repo):$(params.output-image-tag)
    - name: rebuild
      value: $(params.rebuild)
    - name: skip-checks
      value: $(params.skip-checks)
    taskRef:
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:aac8127bc10c95fae3ca1248c1dd96576315f3313bca90c5c9378dbf37954a08
      - name: kind
        value: task
      resolver: bundles

  - name: clone-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    - name: ociStorage
      value: $(params.output-image-repo):konflux-$(params.revision).git
    - name: ociArtifactExpiresAfter
      value: $(params.oci-artifact-expires-after)
    taskRef:
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:0761f97595d42c87c076797e0d0f66ff572146cad958106b7f5446b182d03394
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]
    workspaces:
    - name: basic-auth
      workspace: git-auth

  - name: build-container
    matrix:
      params:
      - name: PLATFORM
        value:
        - $(params.build-platforms)
    params:
    - name: IMAGE
      value: $(params.output-image-repo):$(params.output-image-tag)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: BUILD_ARGS
      value:
      - base_image=$(params.base-image)
      - catalog_dir=$(params.catalog-dir)
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: IMAGE_APPEND_PLATFORM
      value: "true"
    taskRef:
      params:
      - name: name
        value: buildah-remote-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.4@sha256:19a7c9518d9831d60f8b9226ef89428513994659fd124bb2b0d685bff39313ef
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]
    retries: 1

  - name: build-image-index
    params:
    - name: IMAGE
      value: $(params.output-image-repo):$(params.output-image-tag)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: ALWAYS_BUILD_INDEX
      value: $(params.build-image-index)
    - name: IMAGES
      value:
      - $(tasks.build-container.results.IMAGE_REF[*])
    taskRef:
      params:
      - name: name
        value: build-image-index
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.1@sha256:70f2fe8ab9909c2bc8bb853ed5b880969f0de5022658f3af86f7dea15f95ff73
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]

  - name: deprecated-base-image-check
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:eb8136b543147b4a3e88ca3cc661ca6a11e303f35f0db44059f69151beea8496
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: apply-tags
    params:
    - name: IMAGE
      value: $(tasks.build-image-index.results.IMAGE_URL)
    taskRef:
      params:
      - name: name
        value: apply-tags
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:4973fa42a8f06238613447fbdb3d0c55eb2d718fd16f2f2591a577c29c1edb17
      - name: kind
        value: task
      resolver: bundles

  - name: validate-fbc
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
    taskRef:
      params:
      - name: name
        value: validate-fbc
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-validate-fbc:0.1@sha256:4311767f6c448a2e4693f075346a723a47139bb040b30d70bd728df81d009c42
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]
