apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/operator-index?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" || (event == "push" && target_branch == "master")
  labels:
    appstudio.openshift.io/application: acs-operator-index-ocp-v4-13
    appstudio.openshift.io/component: operator-index-ocp-v4-13
    pipelines.appstudio.openshift.io/type: build
  name: operator-index-ocp-v4-13-on-push
  namespace: rh-acs-tenant

spec:

  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: base-image
    value: registry.redhat.io/openshift4/ose-operator-registry:v4.13
  - name: output-image-tag
    value: ocp-v4-13-{{revision}}-fast
  - name: catalog-dir
    value: catalog-bundle-object
  - name: image-expires-after
    value: 13w

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  pipelineRef:
    name: operator-index-pipeline
